In [1]:
import pandas
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split

In [2]:
dataframe = pandas.read_csv("/content/model2v1.csv")
dataframe

Obtained Job Role  1st sem  ...  Technical Blogs  Soft skills and Communication
0                  10     7.00  ...                0                              7
1                  30     9.33  ...                1                             10
2                  30     7.90  ...                1                              7
3                  30     8.25  ...                0                              8
4                  10     7.50  ...                0                              8
..                ...      ...  ...              ...                            ...
66                 20     7.30  ...                1                              7
67                 20     9.33  ...                1                              8
68                 60     7.00  ...                1                              6
69                 60     8.25  ...                0                              9
70                 20     9.00  ...                0                              8

[71 rows x 38 columns]

In [3]:
dataset = dataframe.values
dataset

array([[10.  ,  7.  ,  7.  , ...,  1.  ,  0.  ,  7.  ],
       [30.  ,  9.33,  8.5 , ...,  1.  ,  1.  , 10.  ],
       [30.  ,  7.9 ,  8.1 , ...,  1.  ,  1.  ,  7.  ],
       ...,
       [60.  ,  7.  ,  7.  , ...,  1.  ,  1.  ,  6.  ],
       [60.  ,  8.25,  9.  , ...,  1.  ,  0.  ,  9.  ],
       [20.  ,  9.  ,  9.14, ...,  1.  ,  0.  ,  8.  ]])

In [4]:
X = dataset[:,1:].astype(float)
y = dataset[:,:1].astype(float)

In [5]:
y

array([[10.],
       [30.],
       [30.],
       [30.],
       [10.],
       [50.],
       [30.],
       [ 0.],
       [10.],
       [30.],
       [30.],
       [10.],
       [10.],
       [30.],
       [30.],
       [10.],
       [ 0.],
       [30.],
       [ 0.],
       [30.],
       [ 0.],
       [10.],
       [ 0.],
       [ 0.],
       [30.],
       [30.],
       [30.],
       [ 0.],
       [ 0.],
       [30.],
       [ 0.],
       [10.],
       [30.],
       [ 0.],
       [40.],
       [30.],
       [70.],
       [ 0.],
       [ 0.],
       [30.],
       [ 0.],
       [30.],
       [70.],
       [ 0.],
       [ 0.],
       [30.],
       [ 0.],
       [ 0.],
       [30.],
       [ 0.],
       [ 0.],
       [30.],
       [ 0.],
       [10.],
       [30.],
       [ 0.],
       [40.],
       [30.],
       [70.],
       [ 0.],
       [ 0.],
       [ 0.],
       [30.],
       [ 0.],
       [30.],
       [70.],
       [20.],
       [20.],
       [60.],
       [60.],
       [20.]])

In [6]:
#encode class values as integers
encoder = LabelEncoder()
encoder.fit(y) 
encoded_y = encoder.transform(y)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_y)

y1 = dummy_y
y1

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y1, test_size=0.25)

In [47]:
#model
model = Sequential( )
model.add(Dense(20, input_dim=37, activation='relu'))
model.add(Dense(15, activation='relu'))
model.add(Dense(8, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_30 (Dense)             (None, 20)                760       
_________________________________________________________________
dense_31 (Dense)             (None, 15)                315       
_________________________________________________________________
dense_32 (Dense)             (None, 8)                 128       
Total params: 1,203
Trainable params: 1,203
Non-trainable params: 0
_________________________________________________________________


In [51]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=100, batch_size=10)

Epoch 1/100
6/6 [==============================] - 0s 7ms/step - loss: 0.4784 - accuracy: 0.7679 - val_loss: 1.1932 - val_accuracy: 0.6667
Epoch 2/100
6/6 [==============================] - 0s 3ms/step - loss: 0.4911 - accuracy: 0.7857 - val_loss: 0.8337 - val_accuracy: 0.8000
Epoch 3/100
6/6 [==============================] - 0s 4ms/step - loss: 0.4729 - accuracy: 0.8036 - val_loss: 0.9766 - val_accuracy: 0.8000
Epoch 4/100
6/6 [==============================] - 0s 3ms/step - loss: 0.4199 - accuracy: 0.8036 - val_loss: 0.9996 - val_accuracy: 0.7333
Epoch 5/100
6/6 [==============================] - 0s 3ms/step - loss: 0.4253 - accuracy: 0.7857 - val_loss: 1.0467 - val_accuracy: 0.7333
Epoch 6/100
6/6 [==============================] - 0s 3ms/step - loss: 0.4214 - accuracy: 0.8214 - val_loss: 0.9577 - val_accuracy: 0.7333
Epoch 7/100
6/6 [==============================] - 0s 3ms/step - loss: 0.4768 - accuracy: 0.8036 - val_loss: 1.0894 - val_accuracy: 0.6000
Epoch 8/100
6/6 [==========

In [52]:
model.save('model2.h5')

In [53]:
import tensorflow as tf

model = tf.keras.models.load_model('model2.h5')
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
open("converted_model2.tflite", "wb").write(tflite_model)

INFO:tensorflow:Assets written to: /tmp/tmpz6u8ot07/assets


INFO:tensorflow:Assets written to: /tmp/tmpz6u8ot07/assets


6548